---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/dbrmgzmy/public_html/
    - /bin/cp *.html $DEPLOYPATH
    - /bin/cp *.jpg $DEPLOYPATH
    - /bin/cp *.jpeg $DEPLOYPATH
    - /bin/cp *.txt $DEPLOYPATH
    - /bin/cp *.png $DEPLOYPATH
    - /bin/cp *.ico $DEPLOYPATH
    - /bin/cp *.svg $DEPLOYPATH
    - /bin/cp _next/* $DEPLOYPATH
